### ISSUE TITLE
warning C4101: 'rc'

### ISSUE THREAD

**Issue by blondie63** [simolus3/sqlite3.dart#129] opened 2022-11-05 15:07 UTC
Using last sqlite3_flutter_libs: ^0.5.10
I've this error building windows platform:
C:\Users\Mauro\Documents\__Progetti\Flutter\cmobi\build\windows\_deps\sqlite3-src\sqlite3.c(114636,7): warning C4101: 'rc': variabile locale senza riferimenti [C:\Users\Mauro\Documents\__Progetti\Flutter\cmobi\build\windows\plugins\sqlite3_flutter_libs\sqlite3.vcxproj]
  cl : warning della riga di comando D9002 : l'opzione sconosciuta '-O3' verr� ignorata

How to fix it ?
Thanks

**Comment by simolus3** [comment] 2022-11-05 23:08
This looks like a duplicate of #122. Is this just a warning, or does your build fail because of this? The error comes from sqlite3 itself, but I'll take a look at how to suppress it.

**Closed by simolus3** 2022-11-05 23:08 UTC

**Comment by blondie63** [comment] 2022-11-05 23:15
Build fail because of this

**Comment by simolus3** [comment] 2022-11-05 23:56
I've posted more details in the other issue. If you could check that out it would help a lot.
